server:
  port: 1668

spring:
  application:
    name: platform-boot

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/platform-boot?serverTimezone=GMT%2B8
    username: ${DB_USERNAME:platform-boot}
    password: ${DB_PASSWORD:platform-boot}
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false

  servlet:
    multipart:
      max-file-size: 20MB     # 最大上传单个文件大小 默认 1M
      max-request-size: 100MB  # 最大总上传数据大小 默认 10M


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:**/mapper/xml/*.xml


platform:
  swagger:
    title: platform-boot 接口文档
    version: v1.0 版本
    termsOfService: https://doc.1ddh.cn
    description: platform-boot API接口文档
    name: demain_lee
    url: https://www.1ddh.cn
    email: lmm_work@163.com
    licenseName:
    licenseUrl:

knife4j:
  enable: true                # 开启增强功能
  production: false           # 是否生产环境 如果为true停用Knife4j文档
  basic:
    enable: false             # 开启Swagger的Basic认证功能,默认是false
    username: test            # Basic认证用户名
    password: test            # Basic认证密码
  setting:                    # 自定义footer 版本 >=2.0.8
    enableFooter: false       # 禁用默认 footer显示
    enableFooterCustom: true  # 自定义footer
    # 自定义显示内容
    footerCustomContent: © 2021-2024 [platform-boot](https://www.1ddh.cn)
