server:
  port: 9001

spring:
  application:
    name: platform-resource
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://authorization-server:9000   
          
logging:
  level:
    org.springframework.security: trace
    com.demain.framework.security: DEBUG


platform:
  resource:
    server:
      enabled: true
      enable-method-security: true
      whitelist: 
        - "/messages1"